language: node_js
services:
 - docker
node_js:
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
before_install:
  - docker pull lcinder/order-n-go:prueba
script:
  - docker run -t -v `pwd`:/test lcinder/order-n-go:prueba

